- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i

- name: "Executing Node app with PM2"
  shell: |
    export TYPEORM_ENTITIES=./backend/dist/modules/domain/**/*.entity{.ts,.js}
    export TYPEORM_MIGRATIONS_DIR=./backend/dist/migrations
    export TYPEORM_MIGRATIONS=./backend/dist/migrations/*.ts
    cd /home/ubuntu/backend
    pm2 stop default
    node dist/main.js

  register: execute_node

- name: "print message"
  debug:
    msg: "{{ execute_node.stdout_lines }}"
